version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:144458853229:task-definition/cb-app-task1:40"
        LoadBalancerInfo:
          ContainerName: "teacher"
          ContainerPort: 80
