name: 'Terraform Amazon Teacher Student ECS Fargate Gateway'

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select Action
        options: 
        - create
        - destroy

jobs:
  terraform:
    name: 'Terraform Amazon ECS Fargate'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
          
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=./terraform/aws_fargate_gateway/ init

    # Terraform apply
    - name: Terraform Apply
      if: github.event.inputs.action == 'create'
      run: terraform -chdir=./terraform/aws_fargate_gateway/ apply -auto-approve

    # Terraform destroy
    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform -chdir=./terraform/aws_fargate_gateway/ destroy -auto-approve
